name: Copy File on Push PdP.pdf

on:
  push:
    branches: [main] #puoi specificare qui la branch sulla quale effettuare il push

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy File
        uses: actions/checkout@v2

      - name: Copying file
        run: cp ./latex/esterni/documenti/pianoDiProgetto/PdP.pdf ./documenti_esterni/
      - name: Copying file
        run: cp ./latex/esterni/documenti/glossario/glossario.pdf ./documenti_esterni/ 

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add ./documenti_esterni/PdP.pdf
          git add ./documenti_esterni/glossario.pdf

          git commit -m "update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
