name: Copy File on Push

on:
  push:
    branches: [main] #puoi specificare qui la branch sulla quale effettuare il push

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy File
        uses: actions/checkout@v2

      - name: Copying file PdP.pdf
        run: cp ./latex/documenti_esterni/documenti/pianoDiProgetto/PdP.pdf ./documenti_esterni/documenti/
      - name: Copying file glossario.pdf
        run: cp ./latex/documenti_esterni/documenti/glossario/glossario.pdf ./documenti_esterni/documenti/
      - name: Copying file PdQ.pdf
        run: cp ./latex/documenti_esterni/documenti/pianoDiQualifica/PdQ.pdf ./documenti_esterni/documenti/
      - name: Copying file NdP.pdf
        run: cp ./latex/documenti_interni/documenti/normeDiProgetto/NdP.pdf ./documenti_interni/documenti/
      - name: Copying file AdR.pdf
        run: cp ./latex/documenti_esterni/documenti/analisiDeiRequisiti/AdR.pdf ./documenti_esterni/documenti/

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add ./documenti_esterni/documenti/PdP.pdf
          git add ./documenti_esterni/documenti/glossario.pdf
          git add ./documenti_esterni/documenti/PdQ.pdf
          git add ./documenti_interni/documenti/NdP.pdf
          git add ./documenti_esterni/documenti/AdR.pdf
          
          git commit -m "updateOnPush"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
