name: Copy Files on Push

on:
  push:
    branches: [main] #specificare qui la branch sulla quale effettuare il push

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Files
        uses: actions/checkout@v2

      - name: Copying files Documenti Interni Documenti
        run: find latex/documenti_interni/documenti/ -name "*.pdf" -exec cp {} documenti_interni/documenti/ \;
      - name: Copying files Documenti Esterni Documenti
        run: find latex/documenti_esterni/documenti/ -name "*.pdf" -exec cp {} documenti_esterni/documenti/ \;
      - name: Copying files Documenti Interni Verbali
        run: find latex/documenti_interni/verbali/ -name "*.pdf" -exec cp {} documenti_interni/verbali/ \;
      - name: Copying files Documenti Esterni Verbali
        run: find latex/documenti_esterni/verbali/ -name "*.pdf" -exec cp {} documenti_esterni/verbali/ \;
      - name: Copying files Documenti Esterni Candidatura
        run: find latex/documenti_esterni/candidatura/ -name "*.pdf" -exec cp {} documenti_esterni/candidatura/ \;        

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add *.pdf
          
          git commit -m "updateOnPush"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
